# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.2997796  0.73134899 0.11280568]
  [0.99466338 0.12420325 0.17518854]
  [0.12606217 0.23763753 0.52690833]]

 [[0.79624688 0.97442222 0.88635289]
  [0.46229569 0.12580468 0.71384279]
  [0.05361117 0.59044423 0.16629046]]

 [[0.12386676 0.26262699 0.17366591]
  [0.61387292 0.50611989 0.08658589]
  [0.51179172 0.65572286 0.5296781 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [10]:
y=np.tril(np.arange(1,6),-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [32]:
import numpy as np
print("Checkerboard pattern:")
z = np.zeros((8,8),dtype=int)
z[1::2,::2] = 2
z[::2,1::2] = 2
print(z)

Checkerboard pattern:
[[0 2 0 2 0 2 0 2]
 [2 0 2 0 2 0 2 0]
 [0 2 0 2 0 2 0 2]
 [2 0 2 0 2 0 2 0]
 [0 2 0 2 0 2 0 2]
 [2 0 2 0 2 0 2 0]
 [0 2 0 2 0 2 0 2]
 [2 0 2 0 2 0 2 0]]


# 4. Normalize a 5x5 random matrix

In [1]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.90167161 0.02151229 0.91363806 0.57089457 0.1122898 ]
 [0.69279289 0.66290154 0.28533844 0.7041475  0.65950929]
 [0.41025055 0.78014575 0.073936   0.197045   0.56177046]
 [0.36568101 0.14517002 0.14133518 0.09534395 0.64800831]
 [0.89279225 0.968071   0.84144498 0.6684999  0.94419098]]
After normalization:
[[0.9298518  0.         0.94249385 0.58039958 0.09590267]
 [0.7091801  0.67760112 0.27872137 0.72117577 0.67401736]
 [0.41068584 0.80146477 0.05538347 0.18544302 0.57076034]
 [0.36359997 0.13063926 0.12658791 0.07800008 0.66186705]
 [0.92047113 1.         0.86622487 0.68351556 0.97477175]]


# 5.  How to find common values between two arrays?

In [3]:
import numpy as np
x = np.array([0, 10, 20, 40, 60])
print("Array1: ",x)
y = np.array([10, 30, 40])
print("Array2: ",y)
print("Common values between two arrays:")
print(np.intersect1d(x, y))

Array1:  [ 0 10 20 40 60]
Array2:  [10 30 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [4]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [25]:
x= np.random.randint(0,2,6)
print("First array:",x)
y= np.random.randint(0,2,6)
print("Second array:",y)
comparison = x == y
equal_arrays = comparison.all()

print(equal_arrays)

First array: [1 2 5]
Second array: [1 2 5]
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [26]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.61758184 0.64194558 0.00178136 0.35558606 0.         0.70875305
 0.10431909 0.40646824 0.20826745 0.59420725]


# 9. How to print all the values of an array?

In [31]:
np.set_printoptions(threshold=np.inf)
z = np.random.random((25,25))
print(z)

[[0.56866048 0.88084848 0.78021161 0.13385974 0.8722578  0.77878396
  0.65886189 0.68668811 0.41336182 0.64111081 0.35322733 0.10424644
  0.77558464 0.38845528 0.64767121 0.84827309 0.06252433 0.96596898
  0.93821283 0.18723536 0.59869503 0.92218034 0.88240812 0.25157047
  0.43872475]
 [0.86392008 0.90888985 0.53654297 0.70346438 0.8500487  0.73416438
  0.65458497 0.06965535 0.78006161 0.0072631  0.590079   0.69853925
  0.12881969 0.22348544 0.69933183 0.52912423 0.62607072 0.27175333
  0.30195487 0.21361034 0.11993466 0.58959261 0.67364084 0.09351458
  0.78626459]
 [0.9382758  0.71226064 0.13641622 0.61108426 0.37265031 0.44144271
  0.96559966 0.10002807 0.07882696 0.22183291 0.06777236 0.91130771
  0.94696971 0.95421286 0.38468133 0.59840662 0.6554093  0.18390176
  0.72327229 0.23406863 0.32918613 0.36586875 0.41951692 0.06725505
  0.84746969]
 [0.27692398 0.82769269 0.08782837 0.76631023 0.99744392 0.82424687
  0.97064725 0.03499267 0.60047241 0.31359439 0.58047803 0.42669108
  0.41

# 10.Subtract the mean of each row of a matrix

In [41]:
x = np.random.rand(3, 5)
print(x)
print("mean of each row is :",x.mean(axis=1, keepdims=True))
# Recent versions of numpy
y = x - x.mean(axis=1, keepdims=True)
print("After substracting the mean row of matrix x :")
print(y)

[[0.79566221 0.43002024 0.63679677 0.60439867 0.27249453]
 [0.27436979 0.26652262 0.46600647 0.41135823 0.36187955]
 [0.11337394 0.2081213  0.73221629 0.68441798 0.94244427]]
mean of each row is : [[0.54787449]
 [0.35602733]
 [0.53611476]]
After substracting the mean row of matrix x :
[[ 0.24778772 -0.11785424  0.08892229  0.05652419 -0.27537995]
 [-0.08165755 -0.08950471  0.10997914  0.0553309   0.00585222]
 [-0.42274082 -0.32799346  0.19610154  0.14830322  0.40632952]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [45]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
z += np.bincount(i, minlength=len(z))
print(z)

[3 3 9 1 5 6 5 6 8 1 2 0 8 7 7 8 9 8 6 6]
[2. 3. 2. 3. 1. 3. 5. 3. 5. 3.]


# 12.How to get the diagonal of a dot product?

In [51]:
a = np.random.randint(0,10,(3,3))
b= np.random.randint(0,10,(3,3))
print("First array:")
print(a)
print("Second Array: ")
print(b)
c=np.diag(np.dot(a, b))
print("the diagonal of a dot product of a & b is ")
print(c)

First array:
[[1 2 5]
 [8 9 4]
 [2 9 3]]
Second Array: 
[[9 2 4]
 [8 6 1]
 [5 8 4]]
the diagonal of a dot product of a & b is 
[ 50 102  29]


# 13.How to find the most frequent value in an array?

In [52]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[3 0 3 1 6 7 9 9 1 7 5 5 3 9 7 5 6 7 2 2 6 0 8 9 8 4 1 7 5 2 7 5 0 9 0 3 8
 9 8 8]
Most frequent value in the above array:
7


# 14.How to get the n largest values of an array

In [56]:
import numpy as np
x = np.arange(10)

print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [60]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
